const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
module.exports=async({origin,headers,win,nodeExe,dataDir})=>{
  const checks=[];
  async function request(route,options={},expected=200){const r=await fetch(origin+'/api/oa/'+route,{...options,headers:{...headers,...options.headers}});const v=await r.json();assert.equal(r.status,expected,JSON.stringify(v));return v;}
  const post=b=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
  async function job(id){for(let i=0;i<600;i++){const j=await request('job?id='+id);if(j.state==='completed')return j.result;if(j.state!=='running')throw new Error(j.error);await new Promise(r=>setTimeout(r,200));}throw new Error('job timeout');}
  async function upload(workspace,name,data,replaceId){const params={workspace,name};if(replaceId)params.replaceId=replaceId;const j=await request('import?'+new URLSearchParams(params),{method:'POST',body:data},202);return job(j.jobId);}
  assert.equal((await fetch(origin+'/api/oa/status')).status,403);checks.push('Session authentication required');
  assert.equal((await fetch(origin+'/api/system/update-env',{...post({}),headers})).status,403);checks.push('Unlisted APIs blocked');
  const w=await request('workspaces',post({name:'行政作業知識庫'})),other=await request('workspaces',post({name:'隔離測試'}));
  await request('workspaces',{...post({workspace:other.slug,name:'文件格式驗證'}),method:'PATCH'});checks.push('Workspace creation and rename');
  const fixture=fs.readFileSync(path.join(__dirname,'../fixtures/oa-example.txt'));
  const imported=await upload(w.slug,'行政設備借用.txt',fixture);assert.ok(imported.chunks>0);checks.push('Real Chinese embeddings persisted');
  assert.equal((await upload(w.slug,'重複.txt',fixture)).duplicate,true);checks.push('Duplicate contents skipped');
  const result=await request('search',post({workspace:w.slug,query:'設備可以借用幾天？',limit:3}));assert.match(result.matches[0].text,/十四天/);checks.push('Chinese semantic search returns correct source');
  await request('read',post({workspace:other.slug,documentId:imported.documentId}),400);await request('read',post({workspace:w.slug,documentId:'../../secret'}),400);checks.push('Cross-workspace and arbitrary file access denied');
  await request('reindex',post({workspace:w.slug,documentId:imported.documentId}),202).then(j=>job(j.jobId));checks.push('Reindex retains document identity');
  const temp=await upload(other.slug,'待更新.txt',Buffer.from('測試文件 OLD-CONTENT'));
  await upload(other.slug,'更新文件.txt',Buffer.from('測試文件 NEW-CONTENT'),temp.documentId);
  const changed=await request('read',post({workspace:other.slug,documentId:temp.documentId}));assert.match(changed.text,/NEW-CONTENT/);assert.ok(!changed.text.includes('OLD-CONTENT'));checks.push('Atomic document replacement updates text and index');
  const exportResponse=await fetch(origin+'/api/oa/export?'+new URLSearchParams({workspace:other.slug,documentId:temp.documentId}),{headers});assert.equal(await exportResponse.text(),'測試文件 NEW-CONTENT');checks.push('Original document export exact bytes');
  await request('documents',{...post({workspace:other.slug,documentId:temp.documentId}),method:'DELETE'});await request('read',post({workspace:other.slug,documentId:temp.documentId}),400);checks.push('Document deletion removes source');
  const beforeBackup=await request('status');const backup=await request('backup',post({}));
  const importName='import-'+crypto.randomUUID()+'.sqlite';fs.copyFileSync(path.join(dataDir,'backups',backup.name),path.join(dataDir,'backups',importName));
  const restored=await request('restore',post({name:importName}));assert.equal(restored.workspaces,beforeBackup.workspaces);assert.equal(restored.documents,beforeBackup.documents);checks.push('Consistent backup and non-destructive restore');
  const afterBackup=await request('workspaces');const restoreWorkspace=afterBackup.find(x=>x.name==='行政作業知識庫（還原）');const restoredSearch=await request('search',post({workspace:restoreWorkspace.slug,query:'借用期限'}));assert.match(restoredSearch.matches[0].text,/十四天/);checks.push('Restored embeddings searchable without reindex');
  await request('settings',post({enabled:true,url:'https://example.com/v1',model:'test',maxTokens:512}),400);await request('settings',post({enabled:true,url:'http://127.0.0.1.evil.example:1234/v1',model:'test',maxTokens:512}),400);await request('ask',post({workspace:w.slug,query:'期限？'}),400);checks.push('Remote model URLs rejected; disabled local model makes no request');
  if(process.env.OA_TEST_FORMATS==='1')for(const f of fs.existsSync(path.join(__dirname,'../fixtures/formats.json'))?JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/formats.json'),'utf8')).map(f=>({...f,data:Buffer.from(f.data,'base64')})):await require('./format-test.cjs')()){const d=await upload(other.slug,f.name,f.data);const source=await request('read',post({workspace:other.slug,documentId:d.documentId,length:8000}));assert.ok(source.text.includes(f.marker),f.name+' parser lost text');checks.push('Format content verified: '+f.name);}
  const fakeModel=require('node:http').createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;res.setHeader('Content-Type','application/json');if(req.url==='/v1/models')return res.end(JSON.stringify({data:[{id:'local-test-model'}]}));const value=JSON.parse(text);assert.ok(value.messages[1].content.includes('十四天'));res.end(JSON.stringify({choices:[{message:{content:'設備借用期限為十四天。[1]'}}]}));});
  await new Promise(r=>fakeModel.listen(0,'127.0.0.1',r));
  try{await request('settings',post({enabled:true,url:`http://127.0.0.1:${fakeModel.address().port}/v1`,model:'local-test-model',maxTokens:512}));await request('model-test',post({}));const answer=await request('ask',post({workspace:w.slug,query:'期限？'}));assert.match(answer.answer,/十四天/);assert.ok(answer.sources.length>0);checks.push('Optional local model adapter passes context and returns answer with sources (mock server)');}finally{await request('settings',post({enabled:false,url:'http://127.0.0.1:11434/v1',model:'',maxTokens:1024}));await new Promise(r=>fakeModel.close(r));}
  const longText=Buffer.from('SOURCE-PAGE-ONE\n'+'本機資料閱讀測試。'.repeat(950)+'\nSOURCE-PAGE-TWO');const long=await upload(other.slug,'長文件.txt',longText);
  const page=await request('read',post({workspace:other.slug,documentId:long.documentId,length:8000}));assert.equal(page.nextOffset,8000);const next=await request('read',post({workspace:other.slug,documentId:long.documentId,offset:8000,length:8000}));assert.match(next.text,/SOURCE-PAGE-TWO/);checks.push('Source pagination beyond 8000 characters');
  const cancellation=await request('import?'+new URLSearchParams({workspace:other.slug,name:'取消測試.txt'}),{method:'POST',body:Buffer.from('取消文件，不應保存。'.repeat(3000))},202);await request('cancel',post({id:cancellation.jobId}));let cancelled;for(let i=0;i<100;i++){cancelled=await request('job?id='+cancellation.jobId);if(cancelled.state!=='running')break;await new Promise(r=>setTimeout(r,100));}assert.equal(cancelled.state,'cancelled');assert.ok(!(await request('documents?workspace='+other.slug)).some(d=>d.title==='取消測試.txt'));checks.push('Import cancellation leaves no partial document');
  const config=await request('mcp-config');const cfg=JSON.parse(config.claude).mcpServers['oa-knowledge'];assert.equal(cfg.command,'powershell.exe');assert.ok(!config.claude.includes(dataDir));const mcpProfile=path.join(dataDir,'mcp-test-profile');require('../mcp-config.cjs').register({node:nodeExe,server:path.join(__dirname,'../runtime/mcp.cjs'),data:dataDir,base:path.join(mcpProfile,'OA-Knowledge')});checks.push('Generated MCP config uses universal per-user discovery');
  const {Client}=require('../runtime/node_modules/@modelcontextprotocol/sdk/dist/cjs/client/index.js'),{StdioClientTransport}=require('../runtime/node_modules/@modelcontextprotocol/sdk/dist/cjs/client/stdio.js');
  const client=new Client({name:'oa-test',version:'0.2.0'});try{await client.connect(new StdioClientTransport({command:cfg.command,args:cfg.args,env:{...process.env,LOCALAPPDATA:mcpProfile,OA_DATA_DIR:dataDir},stderr:'pipe'}));const tools=await client.listTools();assert.equal(tools.tools.length,8);const reply=await client.callTool({name:'search_knowledge',arguments:{workspace:w.slug,query:'借用幾天？'}});assert.ok(!reply.isError,JSON.stringify(reply));assert.match(reply.content[0].text,/十四天/);const ws=await client.callTool({name:'list_workspaces',arguments:{offset:0,limit:1}});assert.equal(JSON.parse(ws.content[0].text).length,1);const list=await client.callTool({name:'list_documents',arguments:{workspace:w.slug}});assert.equal(JSON.parse(list.content[0].text).length,1);const read=await client.callTool({name:'read_document',arguments:{workspace:w.slug,documentId:imported.documentId}});assert.match(read.content[0].text,/OA-DEMO/);const local=await client.callTool({name:'ask_local_model',arguments:{workspace:w.slug,query:'期限'}});assert.ok(local.isError);checks.push('Real MCP handshake, eight tools, pagination and source reads');}finally{await client.close();}
  // Synthetic legacy data verifies migration without touching any real 0.1 database.
  const legacyDir=path.join(dataDir,'storage/documents/synthetic-legacy');fs.mkdirSync(legacyDir,{recursive:true});const oldFile=path.join(dataDir,'storage/anythingllm.db');
  if(!fs.existsSync(oldFile)){
    const {DatabaseSync}=require('node:sqlite');const db=new DatabaseSync(oldFile);db.exec('CREATE TABLE workspaces(id INTEGER,name TEXT);CREATE TABLE workspace_documents(workspaceId INTEGER,filename TEXT,docpath TEXT);INSERT INTO workspaces VALUES(1,\'舊版測試\');INSERT INTO workspace_documents VALUES(1,\'舊文件.pdf\',\'synthetic-legacy/source.json\')');db.close();
    fs.writeFileSync(path.join(legacyDir,'source.json'),JSON.stringify({title:'舊文件.pdf',pageContent:'舊版資料測試 LEGACY-PRESERVED，设备借用十四天。'}));
  }
  const oldBytes=fs.readFileSync(oldFile),migration=await request('legacy',post({}),202);const moved=await job(migration.jobId);assert.equal(moved.documents,1);assert.deepEqual(fs.readFileSync(oldFile),oldBytes);const legacyWorkspace=(await request('workspaces')).find(x=>x.name==='舊版測試（舊版）');const legacyDocs=await request('documents?workspace='+legacyWorkspace.slug);assert.ok(legacyDocs[0].title.endsWith('.txt'));const legacyText=await request('read',post({workspace:legacyWorkspace.slug,documentId:legacyDocs[0].id}));assert.match(legacyText.text,/LEGACY-PRESERVED/);checks.push('Legacy 0.1 text migration preserves original database and rebuilds searchable documents');
  // Remove temporary validation workspaces, keeping one meaningful UI example.
  for(const row of await request('workspaces'))if(row.slug!==w.slug)await request('workspaces',{...post({workspace:row.slug}),method:'DELETE'});checks.push('Workspace deletion cascades documents and vectors');
  if(win){
    await win.webContents.executeJavaScript(`localStorage.setItem('oa-workspace',${JSON.stringify(w.slug)});`);await new Promise(r=>{win.webContents.once('did-finish-load',r);win.webContents.reload();});
    async function until(code){for(let i=0;i<100;i++){if(await win.webContents.executeJavaScript(code))return;await new Promise(r=>setTimeout(r,200));}throw new Error('UI not ready: '+code);}
    await until(`document.getElementById('page-title').textContent==='行政作業知識庫' && document.getElementById('status').textContent.startsWith('本機服務就緒')`);
    await win.webContents.executeJavaScript(`document.getElementById('query').value='設備可以借用幾天？';document.getElementById('search-form').requestSubmit();`);await until(`!!document.querySelector('.result') && !document.getElementById('search-button').disabled`);
    await win.webContents.executeJavaScript(`new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))`);await new Promise(r=>setTimeout(r,300));fs.writeFileSync(path.join(dataDir,'desktop-search.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript(`document.getElementById('settings').click()`);await until(`document.getElementById('stats').textContent.includes('1 份文件')`);fs.writeFileSync(path.join(dataDir,'desktop-settings.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript(`document.getElementById('connections').click()`);await until(`document.getElementById('codex-config').textContent.includes('connection.json')`);fs.writeFileSync(path.join(dataDir,'desktop-connections.png'),(await win.webContents.capturePage()).toPNG());checks.push('Desktop search, settings, MCP instructions and native bridge render');
    const {dialog}=require('electron'),save=dialog.showSaveDialog,open=dialog.showOpenDialog;
    const nativeBackup=path.join(dataDir,'native-backup.sqlite'),nativeExport=path.join(dataDir,'native-export.txt');
    try{
      dialog.showSaveDialog=async()=>({canceled:false,filePath:nativeBackup});
      const b=await win.webContents.executeJavaScript('window.oaDesktop.backup()');assert.ok(b.success,JSON.stringify(b));assert.ok(fs.statSync(nativeBackup).size>0);
      dialog.showSaveDialog=async()=>({canceled:false,filePath:nativeExport});
      const x=await win.webContents.executeJavaScript(`window.oaDesktop.exportDocument(${JSON.stringify(w.slug)},${JSON.stringify(imported.documentId)})`);assert.ok(x.success,JSON.stringify(x));assert.deepEqual(fs.readFileSync(nativeExport),fixture);
      dialog.showOpenDialog=async()=>({canceled:false,filePaths:[nativeBackup]});const r=await win.webContents.executeJavaScript('window.oaDesktop.restore()');assert.equal(r.workspaces,1,JSON.stringify(r));
      for(const row of await request('workspaces'))if(row.slug!==w.slug)await request('workspaces',{...post({workspace:row.slug}),method:'DELETE'});
      checks.push('Native preload/IPC backup, restore and original export execute successfully (file dialogs stubbed to test paths)');
    }finally{dialog.showSaveDialog=save;dialog.showOpenDialog=open;}
  }
  const excelFixture=require('../tests/excel-fixture.cjs')(),excelDoc=await upload(w.slug,'部門預算報表.xlsx',excelFixture);
  const inspect=await request('excel/inspect',post({workspace:w.slug,documentId:excelDoc.documentId})),tableId=inspect.tables[0].id;
  assert.equal(inspect.tables[0].columns.find(c=>c.column==='C').label,'金額 / 實際（元）');
  const excelPage=await request('excel/rows',post({workspace:w.slug,documentId:excelDoc.documentId,tableId}));assert.ok(!JSON.stringify(excelPage).includes('SECRET-MARKER'));assert.equal(excelPage.rows[0].cells.find(c=>c.column==='E').display,'80.00%');checks.push('Excel import persists typed rows, merged headers, cached formulas and safe hidden defaults');
  await request('excel/aggregate',post({workspace:w.slug,documentId:excelDoc.documentId,tableId,column:'B'}),400);
  const fixed=await request('excel/reparse',post({workspace:w.slug,documentId:excelDoc.documentId,options:{includeHidden:false,headerRows:{[tableId]:[1,2]}}}),202);await job(fixed.jobId);
  const sum=await request('excel/aggregate',post({workspace:w.slug,documentId:excelDoc.documentId,tableId,column:'B'}));assert.equal(sum.results[0].value,3000);assert.equal(sum.excludedTotals,1);checks.push('Confirmed Excel headers enable deterministic full-table aggregation without double-counting totals');
  const invalidHeader=await request('excel/reparse',post({workspace:w.slug,documentId:excelDoc.documentId,options:{headerRows:{[tableId]:[999]}}}),202);await assert.rejects(job(invalidHeader.jobId),/表頭列/);assert.equal((await request('excel/aggregate',post({workspace:w.slug,documentId:excelDoc.documentId,tableId,column:'B'}))).results[0].value,3000);checks.push('Failed Excel reparse preserves previous structured data and index');
  const structured=await fetch(origin+'/api/oa/excel/export?'+new URLSearchParams({workspace:w.slug,documentId:excelDoc.documentId}),{headers});const structuredBody=await structured.json();assert.equal(structuredBody.parserVersion,3);assert.ok(!JSON.stringify(structuredBody).includes('HIDDEN-COLUMN-MARKER'));checks.push('Structured JSON export preserves schema and excludes hidden cell values');
  const excelClient=new Client({name:'oa-excel-test',version:'0.3.0'});try{await excelClient.connect(new StdioClientTransport({command:cfg.command,args:cfg.args,env:{...process.env,LOCALAPPDATA:mcpProfile,OA_DATA_DIR:dataDir},stderr:'pipe'}));for(const [name,arguments_]of [['inspect_excel',{workspace:w.slug,documentId:excelDoc.documentId}],['read_excel_rows',{workspace:w.slug,documentId:excelDoc.documentId,tableId,limit:1}],['aggregate_excel',{workspace:w.slug,documentId:excelDoc.documentId,tableId,column:'C'}]]){const r=await excelClient.callTool({name,arguments:arguments_});assert.ok(!r.isError,JSON.stringify(r));if(name==='aggregate_excel')assert.equal(JSON.parse(r.content[0].text).results[0].value,2300);}checks.push('Three Excel MCP tools return structure, typed rows and deterministic aggregate results');}finally{await excelClient.close();}
  const excelBackup=await request('backup',post({})),excelRestoreName='import-'+crypto.randomUUID()+'.sqlite';fs.copyFileSync(path.join(dataDir,'backups',excelBackup.name),path.join(dataDir,'backups',excelRestoreName));await request('restore',post({name:excelRestoreName}));const restoredWs=(await request('workspaces')).find(x=>x.slug!==w.slug);const restoredExcel=(await request('documents?workspace='+restoredWs.slug)).find(x=>x.title.endsWith('.xlsx'));const restoredInfo=await request('excel/inspect',post({workspace:restoredWs.slug,documentId:restoredExcel.id}));assert.equal(restoredInfo.tables[0].headerSource,'manual');await request('workspaces',{...post({workspace:restoredWs.slug}),method:'DELETE'});checks.push('Backup/restore retains Excel schema and confirmed header settings');
  if(win){
    const opened=await win.webContents.executeJavaScript(`(async()=>{try{await refresh();await openExcel(${JSON.stringify(excelDoc.documentId)});return {ok:true};}catch(e){return {error:e.stack};}})()`);assert.ok(opened.ok,JSON.stringify(opened));
    assert.ok(await win.webContents.executeJavaScript(`document.getElementById('excel-body').textContent.includes('80.00%')`));
    await win.webContents.executeJavaScript(`new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))`);await new Promise(r=>setTimeout(r,300));fs.writeFileSync(path.join(dataDir,'desktop-excel.png'),(await win.webContents.capturePage()).toPNG());
    const {dialog}=require('electron'),save=dialog.showSaveDialog;const target=path.join(dataDir,'native-excel.json');
    try{dialog.showSaveDialog=async()=>({canceled:false,filePath:target});const exported=await win.webContents.executeJavaScript(`window.oaDesktop.exportExcel(${JSON.stringify(w.slug)},${JSON.stringify(excelDoc.documentId)})`);assert.ok(exported.success,JSON.stringify(exported));assert.equal(JSON.parse(fs.readFileSync(target)).parserVersion,3);}finally{dialog.showSaveDialog=save;}
    checks.push('Excel desktop preview and native JSON export execute successfully');
  }
  return {passed:true,at:new Date().toISOString(),checks,workspace:w.slug,fixture:'Synthetic documents only; no external model client connected'};
};
