const {test}=require('node:test'),assert=require('node:assert/strict'),fixture=require('./excel-fixture.cjs'),{parseExcel}=require('../runtime/excel.cjs'),{chunks}=require('../runtime/embed.cjs');
const query=require('../runtime/excel-query.cjs');
function setup(options){const pages=parseExcel(fixture(),options),book=pages[0].workbook,store={document:(ws,id)=>{if(ws!=='workspace'||id!=='doc')throw new Error('denied');return {name:'test.xlsx',pages:JSON.stringify(pages)};}};return {pages,book,store};}
test('OOXML relationship mapping, hidden exclusions, merged multi-row headers and formatted values',()=>{
 const {pages,book}=setup();assert.equal(book.sheets[0].name,'行政報表');assert.equal(book.sheets.length,1);assert.ok(!JSON.stringify(pages).includes('SECRET-MARKER'));assert.ok(!JSON.stringify(pages).includes('HIDDEN-COLUMN-MARKER'));assert.ok(!JSON.stringify(pages).includes('HIDDEN-ROW-MARKER'));
 const t=book.tables[0];assert.deepEqual(t.headerRows,[1,2]);assert.equal(t.columns.find(c=>c.column==='C').label,'金額 / 實際（元）');assert.equal(t.columns.find(c=>c.column==='A').label,'部門');
 const cells=t.rows.find(r=>r.row===3).cells;assert.equal(cells.find(c=>c.column==='E').display,'80.00%');assert.equal(cells.find(c=>c.column==='B').display,'NT$1,000.00');assert.equal(cells.find(c=>c.column==='D').isoDate,'2023-03-15');
 assert.equal(cells.find(c=>c.column==='C').formula.expression,'=B3*0.8');assert.equal(cells.find(c=>c.column==='C').raw,800);assert.equal(t.rows.find(r=>r.row===6).cells.find(c=>c.column==='B').raw,null);assert.equal(t.rows.find(r=>r.row===7).role,'total');assert.equal(book.missingFormulaResults,1);
 const indexed=chunks(pages);assert.ok(indexed.some(p=>p.text.includes('實際（元）')&&p.text.includes('800')));assert.ok(indexed.filter(p=>p.location.includes('第 3 列')).every(p=>p.text.includes('工作表 行政報表')));
});
test('explicit hidden inclusion and manual header override are preserved',()=>{const {book}=setup({includeHidden:true,headerRows:{'行政報表!A1:F7':[1,2]}});assert.equal(book.sheets.length,2);assert.ok(JSON.stringify(book).includes('HIDDEN-ROW-MARKER'));assert.equal(book.tables[0].headerSource,'manual');});
test('1904 date system and declared Excel Table headers are distinct from guesses',()=>{const pages=parseExcel(fixture({date1904:true,declared:true}));const t=pages[0].workbook.tables.find(t=>t.name==='Costs');assert.equal(t.headerSource,'excel-table');assert.equal(t.requiresReview,false);assert.equal(t.rows.find(r=>r.row===3).cells.find(c=>c.column==='D').isoDate,'2027-03-16');});
test('structured MCP queries aggregate full rows and exclude totals, missing values and other scopes',()=>{
 const {book,store}=setup();const args={workspace:'workspace',documentId:'doc',tableId:book.tables[0].id};assert.throws(()=>query.aggregate(store,{...args,column:'B'}),/表頭尚未確認/);
 const sum=query.aggregate(store,{...args,column:'B',acceptInferredHeaders:true});assert.equal(sum.results[0].value,3000);assert.equal(sum.excludedTotals,1);assert.equal(sum.skippedCells,1);
 const filtered=query.aggregate(store,{...args,column:'C',operation:'sum',filters:[{column:'A',op:'eq',value:'行政'}],acceptInferredHeaders:true});assert.equal(filtered.results[0].value,800);assert.equal(filtered.cachedFormulaValues,1);
 const avg=query.aggregate(store,{...args,column:'E',operation:'average',acceptInferredHeaders:true});assert.equal(avg.results[0].value,0.775);
 const page=query.readRows(store,{...args,limit:1});assert.equal(page.rows.length,1);assert.equal(page.nextOffset,1);assert.equal(page.rows[0].cells[0].ref,'A3');assert.throws(()=>query.inspect(store,{...args,workspace:'other'}),/denied/);
});
test('numeric-first regions never discard data as context before a guessed text footer',()=>{
 const {unzipSync,zipSync,strToU8}=require('../runtime/node_modules/fflate');const files=unzipSync(fixture());files['xl/worksheets/report.xml']=strToU8('<worksheet><sheetData><row r="1"><c r="A1"><v>10</v></c><c r="B1"><v>20</v></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>備註</t></is></c><c r="B2" t="inlineStr"><is><t>資料</t></is></c></row></sheetData></worksheet>');const book=parseExcel(zipSync(files))[0].workbook;assert.deepEqual(book.tables[0].headerRows,[]);assert.equal(book.tables[0].rows[0].cells[0].raw,10);
});
test('hidden middle columns do not detach visible row identifiers and shared formulas remain explicit',()=>{
 const {unzipSync,zipSync,strToU8}=require('../runtime/node_modules/fflate');const files=unzipSync(fixture());files['xl/worksheets/report.xml']=strToU8('<worksheet><cols><col min="2" max="2" hidden="1"/></cols><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>部門</t></is></c><c r="C1" t="inlineStr"><is><t>金額</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>行政</t></is></c><c r="C2"><f t="shared" si="0" ref="C2:C3">A2*2</f><v>10</v></c></row><row r="3"><c r="A3" t="inlineStr"><is><t>業務</t></is></c><c r="C3"><f t="shared" si="0"/><v>20</v></c></row></sheetData></worksheet>');const book=parseExcel(zipSync(files))[0].workbook;assert.equal(book.tables.length,1);assert.deepEqual(book.tables[0].columns.map(c=>c.column),['A','C']);const f=book.tables[0].rows[1].cells[1].formula;assert.equal(f.expression,null);assert.equal(f.sharedMaster.ref,'C2');assert.equal(f.sharedMaster.expression,'A2*2');
});
