'use strict';
const $=id=>document.getElementById(id),e=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let active=null,rows=[],busy=false,jobId=null,cancelBatch=false,rename=false,configs=null,offset=0,docs=[],source=null,replaceId=null;
const post=data=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function api(route,options={}){const r=await fetch('/api/oa/'+route,options);const value=await r.json();if(!r.ok)throw new Error(value.error||'操作失敗');return value;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,8000);}
function status(text){$('status').textContent=text;}
function lock(value){busy=value;for(const id of ['new-workspace','welcome-create','rename-workspace','upload','folder-upload','search-button','delete-workspace','backup','restore','legacy'])$(id).disabled=value;}
function view(id){for(const name of ['welcome','workspace-view','connections-view','settings-view'])$(name).hidden=name!==id;}
function tab(name){$('search-view').hidden=name!=='search';$('documents-view').hidden=name!=='documents';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
function renderWorkspaces(){const filter=$('workspace-filter').value.toLowerCase();$('workspaces').replaceChildren();for(const row of rows.filter(w=>w.name.toLowerCase().includes(filter))){const b=e('button',undefined,'workspace-item'+(row.slug===active?.slug?' active':''));b.append(e('span','▱'),e('span',row.name),e('small',String(row.documentCount)));b.onclick=()=>{if(!busy)select(row).catch(err=>toast(err.message));};$('workspaces').append(b);}$('workspace-count').textContent=rows.length;}
async function refresh(){rows=await api('workspaces');if(active){active=rows.find(w=>w.slug===active.slug)||null;if(active){$('page-title').textContent=active.name;$('document-summary').textContent=`${active.documentCount} 份文件 · 本機索引 · 可透過 MCP 查詢`;}}renderWorkspaces();}
async function select(row){active=row;offset=0;view('workspace-view');tab('search');$('workspace-title').textContent=row.name;$('page-title').textContent=row.name;$('query').value='';$('document-filter').value='';$('results').replaceChildren(e('div','輸入問題或關鍵字，尋找文件中的相關片段。','empty'));localStorage.setItem('oa-workspace',row.slug);await refresh();await renderDocuments();}
function action(label,fn,cls){const b=e('button',label,cls);b.onclick=async()=>{if(busy)return;try{await fn();}catch(err){toast(err.message);}};return b;}
async function renderDocuments(){if(!active)return;docs=await api('documents?'+new URLSearchParams({workspace:active.slug,offset,filter:$('document-filter').value}));$('documents').replaceChildren();for(const d of docs){const row=e('div',undefined,'document-row'),title=e('span',d.title,'file-name');title.append(e('small',`${Math.max(1,Math.round(d.bytes/1024))} KB · ${d.chunks} 個片段 · ${d.characters.toLocaleString()} 字元`,'doc-meta'));const buttons=e('div',undefined,'actions');if(/\.xlsx$/i.test(d.title))buttons.append(action('Excel 結構',()=>openExcel(d.id)));buttons.append(action('閱讀',()=>readSource(d.id,0)),action('匯出',()=>native('exportDocument',active.slug,d.id)),action('更新',()=>{replaceId=d.id;$('replace-picker').click();}),action('重建索引',()=>runReindex(d)),action('刪除',async()=>{if(!confirm(`刪除「${d.title}」的原始檔、文字與索引？既有備份仍會保留。`))return;await api('documents',{...post({workspace:active.slug,documentId:d.id}),method:'DELETE'});await refresh();await renderDocuments();},'danger-link'));row.append(e('span',d.title.split('.').pop().toUpperCase(),'file-icon'),title,buttons);$('documents').append(row);}if(!docs.length)$('documents').append(e('p','沒有符合條件的文件。','search-hint'));$('doc-page').textContent=`第 ${offset/100+1} 頁 · 每頁最多 100 份`;$('doc-prev').disabled=offset===0;$('doc-next').disabled=docs.length<100;}
$('workspace-filter').oninput=renderWorkspaces;let filterTimer;$('document-filter').oninput=()=>{clearTimeout(filterTimer);filterTimer=setTimeout(()=>{if(!busy){offset=0;renderDocuments().catch(err=>toast(err.message));}},250);};
$('doc-prev').onclick=()=>{if(!busy){offset=Math.max(0,offset-100);renderDocuments().catch(err=>toast(err.message));}};$('doc-next').onclick=()=>{if(!busy){offset+=100;renderDocuments().catch(err=>toast(err.message));}};
function create(edit=false){if(busy)return;rename=edit;$('create-title').textContent=edit?'重新命名知識庫':'建立知識庫';$('workspace-name').value=edit?active.name:'';$('create-dialog').showModal();$('workspace-name').focus();}
$('new-workspace').onclick=()=>create();$('welcome-create').onclick=()=>create();$('rename-workspace').onclick=()=>create(true);$('cancel-create').onclick=()=>$('create-dialog').close();
$('create-form').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{const w=await api('workspaces',{...post({name:$('workspace-name').value,workspace:active?.slug}),method:rename?'PATCH':'POST'});$('create-dialog').close();await select(w);}catch(err){toast(err.message);}finally{ev.submitter.disabled=false;}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
async function waitJob(id,label){jobId=id;$('job-panel').hidden=false;$('job-title').textContent=label;for(;;){const j=await api('job?id='+encodeURIComponent(id));$('job-progress').value=j.total?j.done/j.total*100:0;$('job-detail').textContent=j.stage+(j.total?` · ${j.done} / ${j.total}`:'');if(j.state==='completed'){if(j.result?.errors?.length)toast(j.result.errors.length+' 份文件未完成升級，請開啟 Excel 結構檢視後重新解析。');return j.result;}if(['failed','cancelled'].includes(j.state))throw new Error(j.error||'已取消');await new Promise(r=>setTimeout(r,350));}}
$('cancel-job').onclick=async()=>{cancelBatch=true;if(jobId)try{await api('cancel',post({id:jobId}));}catch(err){toast(err.message);}};
async function uploadFiles(files,replace){if(busy||!active)return;const accepted=files.filter(f=>/\.(txt|md|pdf|docx|xlsx|pptx|csv|json)$/i.test(f.name));if(!accepted.length){toast('沒有支援的文件格式。');return;}lock(true);cancelBatch=false;tab('documents');let done=0,duplicates=0;const errors=[];
try{for(const file of accepted){if(cancelBatch)break;try{if(file.size>50*1024*1024)throw new Error('超過 50 MB');status('匯入：'+file.name);const params={workspace:active.slug,name:file.name};if(replace)params.replaceId=replace;const j=await api('import?'+new URLSearchParams(params),{method:'POST',body:file});const result=await waitJob(j.jobId,file.name);if(result.duplicate)duplicates++;else done++;}catch(err){errors.push(file.name+'：'+err.message);}}await refresh();await renderDocuments();status(`完成 ${done} 份 · 重複 ${duplicates} 份 · 失敗 ${errors.length} 份`);if(errors.length)toast(errors.slice(0,3).join('\n'));}finally{jobId=null;$('job-panel').hidden=true;lock(false);}}
$('upload').onclick=()=>$('file-picker').click();$('folder-upload').onclick=()=>$('folder-picker').click();$('dropzone').onclick=()=>{if(!busy)$('file-picker').click();};$('dropzone').onkeydown=ev=>{if(ev.key==='Enter'&&!busy)$('file-picker').click();};
for(const id of ['file-picker','folder-picker','replace-picker'])$(id).onchange=async()=>{try{await uploadFiles([...$(id).files],id==='replace-picker'?replaceId:undefined);}catch(err){toast(err.message);}finally{$(id).value='';}};
for(const n of ['dragenter','dragover'])$('dropzone').addEventListener(n,ev=>{ev.preventDefault();$('dropzone').classList.add('dragging');});$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragging');$('dropzone').ondrop=ev=>{ev.preventDefault();$('dropzone').classList.remove('dragging');uploadFiles([...ev.dataTransfer.files]).catch(err=>toast(err.message));};window.addEventListener('dragover',ev=>ev.preventDefault());window.addEventListener('drop',ev=>ev.preventDefault());
async function runReindex(d){lock(true);try{const j=await api('reindex',post({workspace:active.slug,documentId:d.id}));await waitJob(j.jobId,'重建 '+d.title);toast('索引重建完成');await renderDocuments();}finally{lock(false);jobId=null;$('job-panel').hidden=true;}}
function results(matches){for(const [i,m]of matches.entries()){const card=e('article',undefined,'result'),h=e('div',undefined,'result-header');h.append(e('span',`[${i+1}]`,'result-index'),e('span',m.title+' · '+m.location),e('small','語意相似度 '+Math.round(m.similarity*100)+'%'));card.append(h,e('p',m.text),action('閱讀完整來源 →',()=>readSource(m.documentId,0)));$('results').append(card);}}
$('search-form').onsubmit=async ev=>{ev.preventDefault();if(busy||!active)return;lock(true);status($('use-model').checked?'正在本機搜尋與生成回答…':'正在本機搜尋…');$('results').replaceChildren(e('p','處理中…','search-hint'));try{const model=$('use-model').checked,r=await api(model?'ask':'search',post({workspace:active.slug,query:$('query').value.trim(),limit:5}));$('results').replaceChildren();if(model){const a=e('article',undefined,'answer');a.append(e('div','本機模型回答 · '+(r.model||''),'answer-title'),e('div',r.answer));$('results').append(a);}const matches=model?r.sources:r.matches;$('results').append(e('p',`${matches.length} 個來源片段 · 請核對原文`,'result-count'));results(matches);if(!matches.length)$('results').append(e('p','沒有可搜尋的文件，請先匯入。','empty'));status('完成 · 本機處理');}catch(err){$('results').replaceChildren(e('p',err.message,'search-hint'));status('操作失敗');}finally{lock(false);}};
async function readSource(id,start){source=await api('read',post({workspace:active.slug,documentId:id,offset:start,length:8000}));$('source-title').textContent=source.title;$('source-text').textContent=source.text;$('source-range').textContent=`${start+1}–${Math.min(start+8000,source.totalCharacters)} / ${source.totalCharacters}`;$('source-prev').disabled=start===0;$('source-next').disabled=source.nextOffset===null;if(!$('source-dialog').open)$('source-dialog').showModal();$('source-text').scrollTop=0;}
$('source-prev').onclick=()=>readSource(source.documentId,Math.max(0,source.offset-8000)).catch(err=>toast(err.message));$('source-next').onclick=()=>readSource(source.documentId,source.nextOffset).catch(err=>toast(err.message));$('close-source').onclick=()=>$('source-dialog').close();
$('delete-workspace').onclick=async()=>{if(busy||!active||!confirm(`刪除「${active.name}」全部文件與索引？此操作無法復原，請先備份。`))return;try{await api('workspaces',{...post({workspace:active.slug}),method:'DELETE'});active=null;localStorage.removeItem('oa-workspace');view('welcome');$('workspace-title').textContent='開始建立你的知識庫';await refresh();}catch(err){toast(err.message);}};
$('connections').onclick=async()=>{if(busy)return;view('connections-view');$('workspace-title').textContent='連接 AI 工具';try{configs=await api('mcp-config');$('codex-config').textContent=configs.codex;$('claude-config').textContent=configs.claude;}catch(err){toast(err.message);}};
for(const kind of ['codex','claude'])$('copy-'+kind).onclick=async()=>{try{await navigator.clipboard.writeText(configs[kind]);toast('已複製設定。');}catch{toast('請選取設定文字，按 Ctrl+C 複製。');}};
async function settings(){view('settings-view');$('workspace-title').textContent='設定與備份';const s=await api('settings'),info=await api('status');$('stats').textContent=`${info.workspaces} 個知識庫 · ${info.documents} 份文件 · ${info.chunks} 個片段`;$('data-path').textContent=info.storage;$('legacy').hidden=!info.legacy;$('model-enabled').checked=s.enabled;$('model-url').value=s.url;$('model-id').value=s.model;$('model-tokens').value=s.maxTokens;}
$('settings').onclick=()=>{if(!busy)settings().catch(err=>toast(err.message));};
async function native(method,...args){if(!window.oaDesktop)throw new Error('請在 Windows 桌面程式中操作');const r=await window.oaDesktop[method](...args);if(r.error)throw new Error(r.error);if(!r.cancelled)toast(r.path?'已儲存：'+r.path:r.workspaces!==undefined?`已還原 ${r.workspaces} 個知識庫、${r.documents} 份文件`:'已完成');return r;}
for(const [id,method]of [['backup','backup'],['restore','restore'],['open-data','openData']])$(id).onclick=async()=>{if(busy)return;lock(true);try{await native(method);await refresh();await settings();}catch(err){toast(err.message);}finally{lock(false);}};
$('model-form').onsubmit=async ev=>{ev.preventDefault();try{const s=await api('settings',post({enabled:$('model-enabled').checked,url:$('model-url').value.trim(),model:$('model-id').value.trim(),maxTokens:Number($('model-tokens').value)}));$('model-state').textContent=s.enabled?'本機模型：'+s.model:'預設只搜尋原文，不呼叫回答模型';toast('本機模型設定已儲存');}catch(err){toast(err.message);}};
$('model-test').onclick=async()=>{$('model-test').disabled=true;$('model-test-result').textContent='正在測試已儲存的本機設定…';try{const r=await api('model-test',post({}));$('model-test-result').textContent='連線成功。可用模型：'+(r.data||[]).map(m=>m.id).join('、');}catch(err){$('model-test-result').textContent=err.message;}finally{$('model-test').disabled=false;}};
$('legacy').onclick=async()=>{if(busy||!confirm('匯入 0.1 版資料並重新建立索引？舊版資料會保留，多次執行會新增多組知識庫。'))return;lock(true);try{const j=await api('legacy',post({})),r=await waitJob(j.jobId,'匯入舊版資料');toast(`已匯入 ${r.documents} 份文件`);await refresh();await settings();}catch(err){toast(err.message);}finally{lock(false);jobId=null;$('job-panel').hidden=true;}};
(async()=>{try{const info=await api('status');$('storage-label').textContent=info.storage;await refresh();const saved=rows.find(w=>w.slug===localStorage.getItem('oa-workspace'));if(saved)await select(saved);status('本機服務就緒 · MCP 可讀取知識庫');if(info.job){lock(true);try{await waitJob(info.job,'恢復作業進度');await refresh();if(active)await renderDocuments();}finally{lock(false);jobId=null;$('job-panel').hidden=true;}}}catch(err){status(err.message);toast(err.message);}})();
